import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "./SessionProviderWrapper";
import { getServerSession } from "next-auth";
import { HeroProvider } from "./providers"; // <-- dosya adını düzelttik



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

 export const metadata = {
   title: "Culinary",
   description: "Generated by Juniustech",
 };


export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="tr" className="light">

    <html lang="en" className="light">
      <head>
        {/* Material Symbols (Landing'deki ikonlar için gerekli) */}
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased bg-background text-foreground font-display`}
      >
        <SessionProviderWrapper session={session}>
          <HeroProvider>
            {children}
          </HeroProvider>
        </SessionProviderWrapper>

        {/* 
        <FrappeProvider
          socketPort={process.env.NEXT_PUBLIC_SOCKET_PORT}
          siteName={process.env.NEXT_PUBLIC_SITE_NAME}
          url="http://63.176.180.142:8001/"
        >
        </FrappeProvider> 
        */}
      </body>
    </html>
  );
}
