import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "./SessionProviderWrapper";
import { getServerSession } from "next-auth";
import { HeroProvider } from "./provders";


// import { FrappeProvider } from "frappe-react-sdk";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
 };

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper session={session}>
          <HeroProvider>
           {children}
          </HeroProvider>
        </SessionProviderWrapper>
        {/* <FrappeProvider
          socketPort={process.env.NEXT_PUBLIC_SOCKET_PORT}
          siteName={process.env.NEXT_PUBLIC_SITE_NAME}
          url='http://63.176.180.142:8001/'
        > */}
          
        {/* </FrappeProvider> */}
      </body>
    </html>
  );
}
